# Generated by Django 5.2 on 2025-05-07 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawg_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('games_count', models.PositiveIntegerField(blank=True, null=True)),
                ('image_background', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawg_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('games_count', models.PositiveIntegerField(blank=True, null=True)),
                ('image_background', models.URLField(blank=True, max_length=500, null=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('year_start', models.PositiveIntegerField(blank=True, null=True)),
                ('year_end', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawg_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('games_count', models.PositiveIntegerField(blank=True, null=True)),
                ('image_background', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawg_id', models.PositiveIntegerField(unique=True)),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('released', models.DateField(blank=True, null=True)),
                ('tba', models.BooleanField(default=False)),
                ('background_image', models.URLField(blank=True, max_length=500, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('rating_top', models.PositiveIntegerField(default=0)),
                ('ratings_count', models.PositiveIntegerField(default=0)),
                ('metacritic', models.PositiveIntegerField(blank=True, null=True)),
                ('playtime', models.PositiveIntegerField(default=0)),
                ('suggestions_count', models.PositiveIntegerField(default=0)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('esrb_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('developers', models.ManyToManyField(blank=True, to='store.developer')),
                ('platforms', models.ManyToManyField(blank=True, to='store.platform')),
                ('tags', models.ManyToManyField(blank=True, to='store.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Addition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawg_id', models.IntegerField(unique=True)),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=255)),
                ('released', models.DateField(blank=True, null=True)),
                ('background_image', models.URLField(blank=True, max_length=500, null=True)),
                ('metacritic', models.IntegerField(blank=True, null=True)),
                ('playtime', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('rating_top', models.IntegerField(default=0)),
                ('esrb_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additions', to='store.game')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('percent', models.FloatField(default=0.0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='store.game')),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('preview', models.URLField()),
                ('video_url', models.URLField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailers', to='store.game')),
            ],
        ),
    ]
