# Generated by Django 5.1.6 on 2025-05-13 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_gamekey_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamekey',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.game'),
        ),
        migrations.AlterField(
            model_name='gamekey',
            name='key',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
