# Generated by Django 5.2.1 on 2025-05-21 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_activationkey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
