# Generated by Django 5.2.1 on 2025-05-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_game_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='rawg_id',
            field=models.PositiveIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
